import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  const defaultTenant = await prisma.tenant.upsert({
    where: { subdomain: 'default' },
    update: {},
    create: {
      name: 'Default Cooperative',
      slug: 'default',
      subdomain: 'default',
      isActive: true,
    },
  });

  const users = [
    {
      email: 'superadmin@dairycoop.com',
      password: 'SuperAdmin@123',
      firstName: 'Super',
      lastName: 'Administrator',
      role: 'SUPER_ADMIN',
      phoneNumber: '+254700000001',
    },
    {
      email: 'admin@dairycoop.com',
      password: 'Admin@123',
      firstName: 'Admin',
      lastName: 'User',
      role: 'ADMIN',
      phoneNumber: '+254700000009',
    },
    {
      email: 'manager@dairycoop.com',
      password: 'Manager@123',
      firstName: 'John',
      lastName: 'Kamau',
      role: 'MANAGER',
      phoneNumber: '+254700000002',
    },
    {
      email: 'collection@dairycoop.com',
      password: 'Collection@123',
      firstName: 'Peter',
      lastName: 'Mwangi',
      role: 'OPERATOR',
      phoneNumber: '+254700000003',
    },
    {
      email: 'accountant@dairycoop.com',
      password: 'Accountant@123',
      firstName: 'Jane',
      lastName: 'Wanjiku',
      role: 'ACCOUNTANT',
      phoneNumber: '+254700000004',
    },
    {
      email: 'store@dairycoop.com',
      password: 'Store@123',
      firstName: 'David',
      lastName: 'Ochieng',
      role: 'STORE_MANAGER',
      phoneNumber: '+254700000005',
    },
    {
      email: 'vet@dairycoop.com',
      password: 'Vet@123',
      firstName: 'Dr. Sarah',
      lastName: 'Njeri',
      role: 'VETERINARIAN',
      phoneNumber: '+254700000006',
    },
    {
      email: 'farmer@dairycoop.com',
      password: 'Farmer@123',
      firstName: 'James',
      lastName: 'Kiprop',
      role: 'FARMER',
      phoneNumber: '+254700000007',
    },
    {
      email: 'customer@dairycoop.com',
      password: 'Customer@123',
      firstName: 'Mary',
      lastName: 'Achieng',
      role: 'CUSTOMER',
      phoneNumber: '+254700000008',
    },
  ];

  for (const userData of users) {
    const hashedPassword = await bcrypt.hash(userData.password, 12);

    await prisma.user.upsert({
      where: {
        tenantId_email: {
          tenantId: defaultTenant.id,
          email: userData.email,
        },
      },
      update: {},
      create: {
        email: userData.email,
        passwordHash: hashedPassword,
        firstName: userData.firstName,
        lastName: userData.lastName,
        phoneNumber: userData.phoneNumber,
        role: userData.role,
        tenantId: defaultTenant.id,
        isEmailVerified: true,
        isActive: true,
      },
    });

    console.log(`✓ Created user: ${userData.email} (${userData.role})`);
  }

  const dairyProducts = [
    {
      itemCode: 'MILK-001',
      itemName: 'Fresh Whole Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 500,
      minStock: 50,
      maxStock: 1000,
      unitPrice: 60,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400',
    },
    {
      itemCode: 'MILK-002',
      itemName: 'Skimmed Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 300,
      minStock: 30,
      maxStock: 600,
      unitPrice: 55,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    },
    {
      itemCode: 'MILK-003',
      itemName: 'Low-Fat Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 250,
      minStock: 25,
      maxStock: 500,
      unitPrice: 58,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400',
    },
    {
      itemCode: 'MILK-004',
      itemName: 'Organic Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 200,
      minStock: 20,
      maxStock: 400,
      unitPrice: 85,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    },
    {
      itemCode: 'MILK-005',
      itemName: 'Chocolate Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 180,
      minStock: 20,
      maxStock: 350,
      unitPrice: 75,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1520338258196-a5e94d8cda4c?w=400',
    },
    {
      itemCode: 'MILK-006',
      itemName: 'Almond Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 150,
      minStock: 15,
      maxStock: 300,
      unitPrice: 120,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1564002429959-b4bc6e68a9e3?w=400',
    },
    {
      itemCode: 'YOGURT-001',
      itemName: 'Plain Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 150,
      minStock: 20,
      maxStock: 300,
      unitPrice: 120,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    },
    {
      itemCode: 'YOGURT-002',
      itemName: 'Strawberry Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 100,
      minStock: 15,
      maxStock: 200,
      unitPrice: 150,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1571212515416-fca5ec2c9490?w=400',
    },
    {
      itemCode: 'YOGURT-003',
      itemName: 'Mango Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 80,
      minStock: 15,
      maxStock: 200,
      unitPrice: 150,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1623948001761-76c4fe0b9ec6?w=400',
    },
    {
      itemCode: 'YOGURT-004',
      itemName: 'Blueberry Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 90,
      minStock: 15,
      maxStock: 200,
      unitPrice: 155,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1562155955-1cb2d73488d7?w=400',
    },
    {
      itemCode: 'YOGURT-005',
      itemName: 'Greek Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 70,
      minStock: 10,
      maxStock: 150,
      unitPrice: 180,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1629707794387-7da8e6917bd8?w=400',
    },
    {
      itemCode: 'YOGURT-006',
      itemName: 'Peach Yogurt',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 75,
      minStock: 10,
      maxStock: 150,
      unitPrice: 150,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1610706931311-e6e6b52ea2b6?w=400',
    },
    {
      itemCode: 'BUTTER-001',
      itemName: 'Salted Butter',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 75,
      minStock: 10,
      maxStock: 150,
      unitPrice: 450,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
    },
    {
      itemCode: 'BUTTER-002',
      itemName: 'Unsalted Butter',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 60,
      minStock: 10,
      maxStock: 120,
      unitPrice: 450,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1596040008861-5f635c9c7261?w=400',
    },
    {
      itemCode: 'BUTTER-003',
      itemName: 'Garlic Butter',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 40,
      minStock: 5,
      maxStock: 80,
      unitPrice: 500,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1547487307-810dffdb87ea?w=400',
    },
    {
      itemCode: 'BUTTER-004',
      itemName: 'Herb Butter',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 5,
      maxStock: 70,
      unitPrice: 520,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1594005103988-8e51bc0e6b5a?w=400',
    },
    {
      itemCode: 'CHEESE-001',
      itemName: 'Cheddar Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 40,
      minStock: 5,
      maxStock: 100,
      unitPrice: 800,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400',
    },
    {
      itemCode: 'CHEESE-002',
      itemName: 'Mozzarella Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 5,
      maxStock: 80,
      unitPrice: 850,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400',
    },
    {
      itemCode: 'CHEESE-003',
      itemName: 'Gouda Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 25,
      minStock: 5,
      maxStock: 60,
      unitPrice: 900,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400',
    },
    {
      itemCode: 'CHEESE-004',
      itemName: 'Parmesan Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 30,
      minStock: 5,
      maxStock: 70,
      unitPrice: 1200,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400',
    },
    {
      itemCode: 'CHEESE-005',
      itemName: 'Swiss Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 20,
      minStock: 5,
      maxStock: 50,
      unitPrice: 950,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1587972373516-601b68dd78d0?w=400',
    },
    {
      itemCode: 'CHEESE-006',
      itemName: 'Blue Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 15,
      minStock: 3,
      maxStock: 40,
      unitPrice: 1100,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=400',
    },
    {
      itemCode: 'CHEESE-007',
      itemName: 'Cream Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 45,
      minStock: 8,
      maxStock: 90,
      unitPrice: 750,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1616197840116-e2b089f5e0b4?w=400',
    },
    {
      itemCode: 'CHEESE-008',
      itemName: 'Feta Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 28,
      minStock: 5,
      maxStock: 60,
      unitPrice: 880,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1631641553064-7f95a2f880ad?w=400',
    },
    {
      itemCode: 'GHEE-001',
      itemName: 'Pure Cow Ghee',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 50,
      minStock: 10,
      maxStock: 100,
      unitPrice: 650,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1614967270507-45e0c4e0a3da?w=400',
    },
    {
      itemCode: 'GHEE-002',
      itemName: 'Organic Ghee',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 8,
      maxStock: 70,
      unitPrice: 850,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1612786115093-4c0f63cc9b7d?w=400',
    },
    {
      itemCode: 'CREAM-001',
      itemName: 'Heavy Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 45,
      minStock: 10,
      maxStock: 100,
      unitPrice: 250,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1628337162723-cb0f5c138c64?w=400',
    },
    {
      itemCode: 'CREAM-002',
      itemName: 'Whipping Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 40,
      minStock: 10,
      maxStock: 90,
      unitPrice: 280,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1594005305639-2f16b2d4fcaa?w=400',
    },
    {
      itemCode: 'CREAM-003',
      itemName: 'Sour Cream',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 30,
      minStock: 8,
      maxStock: 70,
      unitPrice: 220,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1589203928886-8a1e67316ca0?w=400',
    },
    {
      itemCode: 'PANEER-001',
      itemName: 'Fresh Paneer',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 30,
      minStock: 5,
      maxStock: 80,
      unitPrice: 350,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1631452180539-96aca7d48617?w=400',
    },
    {
      itemCode: 'PANEER-002',
      itemName: 'Spiced Paneer',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 25,
      minStock: 5,
      maxStock: 60,
      unitPrice: 380,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    },
    {
      itemCode: 'CURD-001',
      itemName: 'Fresh Curd',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 100,
      minStock: 15,
      maxStock: 200,
      unitPrice: 80,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1625081063176-a45e2e5e2c33?w=400',
    },
    {
      itemCode: 'CURD-002',
      itemName: 'Set Curd',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 85,
      minStock: 12,
      maxStock: 180,
      unitPrice: 85,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1579034963892-388c821d1d9f?w=400',
    },
    {
      itemCode: 'LASSI-001',
      itemName: 'Sweet Lassi',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 60,
      minStock: 10,
      maxStock: 120,
      unitPrice: 70,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1569418110787-2b06209a2945?w=400',
    },
    {
      itemCode: 'LASSI-002',
      itemName: 'Mango Lassi',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 50,
      minStock: 10,
      maxStock: 100,
      unitPrice: 90,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400',
    },
    {
      itemCode: 'LASSI-003',
      itemName: 'Rose Lassi',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 45,
      minStock: 8,
      maxStock: 90,
      unitPrice: 85,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1615478842197-5d5e6c62c9a0?w=400',
    },
    {
      itemCode: 'LASSI-004',
      itemName: 'Salted Lassi',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 40,
      minStock: 8,
      maxStock: 80,
      unitPrice: 65,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1623428454614-abaf00244e52?w=400',
    },
    {
      itemCode: 'ICECREAM-001',
      itemName: 'Vanilla Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 40,
      minStock: 10,
      maxStock: 100,
      unitPrice: 350,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
    },
    {
      itemCode: 'ICECREAM-002',
      itemName: 'Chocolate Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 35,
      minStock: 10,
      maxStock: 90,
      unitPrice: 380,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400',
    },
    {
      itemCode: 'ICECREAM-003',
      itemName: 'Strawberry Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 32,
      minStock: 8,
      maxStock: 80,
      unitPrice: 370,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400',
    },
    {
      itemCode: 'ICECREAM-004',
      itemName: 'Mango Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 38,
      minStock: 10,
      maxStock: 85,
      unitPrice: 390,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1623340466330-79128e126f7f?w=400',
    },
    {
      itemCode: 'ICECREAM-005',
      itemName: 'Butter Scotch Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 28,
      minStock: 8,
      maxStock: 70,
      unitPrice: 400,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?w=400',
    },
    {
      itemCode: 'ICECREAM-006',
      itemName: 'Pistachio Ice Cream',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 25,
      minStock: 5,
      maxStock: 60,
      unitPrice: 450,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1560008581-09b9d8c91e3d?w=400',
    },
    {
      itemCode: 'MILKSHAKE-001',
      itemName: 'Chocolate Milkshake',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 50,
      minStock: 10,
      maxStock: 100,
      unitPrice: 100,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400',
    },
    {
      itemCode: 'MILKSHAKE-002',
      itemName: 'Vanilla Milkshake',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 45,
      minStock: 10,
      maxStock: 90,
      unitPrice: 95,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1603569283847-aa295f0d016a?w=400',
    },
    {
      itemCode: 'MILKSHAKE-003',
      itemName: 'Strawberry Milkshake',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 40,
      minStock: 8,
      maxStock: 85,
      unitPrice: 105,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1622484211871-e9e6ccb35e43?w=400',
    },
    {
      itemCode: 'MILKSHAKE-004',
      itemName: 'Banana Milkshake',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 42,
      minStock: 8,
      maxStock: 80,
      unitPrice: 98,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400',
    },
    {
      itemCode: 'BUTTERMILK-001',
      itemName: 'Plain Buttermilk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 60,
      minStock: 12,
      maxStock: 120,
      unitPrice: 55,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?w=400',
    },
    {
      itemCode: 'BUTTERMILK-002',
      itemName: 'Spiced Buttermilk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 55,
      minStock: 10,
      maxStock: 110,
      unitPrice: 60,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1596816020412-b346e8db3e93?w=400',
    },
    {
      itemCode: 'CUSTARD-001',
      itemName: 'Vanilla Custard',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 8,
      maxStock: 70,
      unitPrice: 200,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1587248721879-ee3068c2e8b3?w=400',
    },
    {
      itemCode: 'CUSTARD-002',
      itemName: 'Chocolate Custard',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 30,
      minStock: 6,
      maxStock: 65,
      unitPrice: 210,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=400',
    },
    {
      itemCode: 'PUDDING-001',
      itemName: 'Rice Pudding',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 40,
      minStock: 8,
      maxStock: 80,
      unitPrice: 180,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1520219305471-aa663778e8e3?w=400',
    },
    {
      itemCode: 'PUDDING-002',
      itemName: 'Caramel Pudding',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 7,
      maxStock: 75,
      unitPrice: 190,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1567327421753-abf33f896e64?w=400',
    },
    {
      itemCode: 'CONDENSED-001',
      itemName: 'Sweetened Condensed Milk',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 55,
      minStock: 10,
      maxStock: 110,
      unitPrice: 280,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1606312619070-d48b6ba0127c?w=400',
    },
    {
      itemCode: 'EVAPORATED-001',
      itemName: 'Evaporated Milk',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 50,
      minStock: 10,
      maxStock: 100,
      unitPrice: 150,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=400',
    },
    {
      itemCode: 'KEFIR-001',
      itemName: 'Plain Kefir',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 30,
      minStock: 5,
      maxStock: 60,
      unitPrice: 140,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1567155763-e98efc21a728?w=400',
    },
    {
      itemCode: 'KEFIR-002',
      itemName: 'Flavored Kefir',
      category: 'OTHER',
      unit: 'Liter',
      currentStock: 25,
      minStock: 5,
      maxStock: 55,
      unitPrice: 160,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1563469621-28fbe59bb7f7?w=400',
    },
    {
      itemCode: 'COTTAGE-001',
      itemName: 'Cottage Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 32,
      minStock: 6,
      maxStock: 70,
      unitPrice: 320,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1589985269112-129304bf0c3f?w=400',
    },
    {
      itemCode: 'RICOTTA-001',
      itemName: 'Ricotta Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 28,
      minStock: 5,
      maxStock: 60,
      unitPrice: 780,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1587842378379-c3e6e57afc6e?w=400',
    },
    {
      itemCode: 'MASCARPONE-001',
      itemName: 'Mascarpone Cheese',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 20,
      minStock: 4,
      maxStock: 50,
      unitPrice: 1250,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400',
    },
    {
      itemCode: 'WHEY-001',
      itemName: 'Whey Protein Powder',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 45,
      minStock: 8,
      maxStock: 90,
      unitPrice: 1800,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400',
    },
    {
      itemCode: 'PEDA-001',
      itemName: 'Milk Peda',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 38,
      minStock: 7,
      maxStock: 80,
      unitPrice: 450,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=400',
    },
    {
      itemCode: 'BURFI-001',
      itemName: 'Milk Burfi',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 35,
      minStock: 6,
      maxStock: 75,
      unitPrice: 480,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400',
    },
    {
      itemCode: 'KHEER-001',
      itemName: 'Ready-to-Eat Kheer',
      category: 'OTHER',
      unit: 'kg',
      currentStock: 42,
      minStock: 8,
      maxStock: 85,
      unitPrice: 220,
      status: 'IN_STOCK',
      imageUrl: 'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=400',
    },
  ];

  for (const product of dairyProducts) {
    const totalValue = Number(product.currentStock) * Number(product.unitPrice);
    
    await prisma.inventoryItem.upsert({
      where: {
        tenantId_itemCode: {
          tenantId: defaultTenant.id,
          itemCode: product.itemCode,
        },
      },
      update: {},
      create: {
        ...product,
        totalValue,
        tenantId: defaultTenant.id,
      },
    });

    console.log(`✓ Created product: ${product.itemName} (${product.itemCode})`);
  }

  console.log('\n✅ Seed completed successfully!');
  console.log(`📦 Total products: ${dairyProducts.length}`);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
