import type { MenuItem } from '../types';
import { UserRole } from '../types';

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'home',
    path: '/dashboard',
  },
  {
    id: 'customer-portal',
    label: 'Customer Portal',
    icon: 'shopping-bag',
    path: '/dashboard/customer-portal',
    permissions: [UserRole.CUSTOMER],
  },
  {
    id: 'farmers',
    label: 'Farmer Management',
    icon: 'users',
    path: '/dashboard/farmers',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.OPERATOR, UserRole.FARMER],
  },
  {
    id: 'milk-collection',
    label: 'Milk Collection',
    icon: 'droplet',
    path: '/dashboard/milk-collection',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.OPERATOR],
  },
  {
    id: 'quality',
    label: 'Milk Quality',
    icon: 'award',
    path: '/dashboard/quality',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.OPERATOR],
  },
  {
    id: 'payments',
    label: 'Payments',
    icon: 'credit-card',
    path: '/dashboard/payments',
    permissions: [UserRole.ADMIN, UserRole.ACCOUNTANT],
  },
  {
    id: 'loans',
    label: 'Loans',
    icon: 'bank',
    path: '/dashboard/loans',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'shares',
    label: 'Share Management',
    icon: 'trending-up',
    path: '/dashboard/shares',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.FARMER],
  },
  {
    id: 'veterinary',
    label: 'Veterinary',
    icon: 'heart-pulse',
    path: '/dashboard/veterinary',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.VETERINARIAN, UserRole.FARMER],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    icon: 'package',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.STORE_MANAGER],
    children: [
      {
        id: 'feed-store',
        label: 'Feed Store',
        icon: 'shopping-bag',
        path: '/dashboard/inventory/feed-store',
      },
      {
        id: 'warehouse',
        label: 'Warehouse',
        icon: 'warehouse',
        path: '/dashboard/inventory/warehouse',
      },
      {
        id: 'stock',
        label: 'Stock Management',
        icon: 'boxes',
        path: '/dashboard/inventory/stock',
      },
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    icon: 'shopping-cart',
    path: '/dashboard/procurement',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'fleet',
    label: 'Fleet Management',
    icon: 'truck',
    path: '/dashboard/fleet',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'hr',
    label: 'Human Resources',
    icon: 'user-check',
    path: '/dashboard/hr',
    permissions: [UserRole.ADMIN],
  },
  {
    id: 'accounting',
    label: 'Accounting',
    icon: 'calculator',
    path: '/dashboard/accounting',
    permissions: [UserRole.ADMIN, UserRole.ACCOUNTANT],
  },
  {
    id: 'customers',
    label: 'Customers',
    icon: 'user-circle',
    path: '/dashboard/customers',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'meetings',
    label: 'Meetings',
    icon: 'calendar',
    path: '/dashboard/meetings',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: 'file-text',
    path: '/dashboard/reports',
    permissions: [UserRole.ADMIN, UserRole.MANAGER, UserRole.ACCOUNTANT],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: 'bar-chart',
    path: '/dashboard/analytics',
    permissions: [UserRole.ADMIN, UserRole.MANAGER],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: 'settings',
    path: '/dashboard/settings',
    permissions: [UserRole.ADMIN],
  },
];
